language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
before_script:
    - composer install
script:
  - ./vendor/bin/phpunit tests/ --coverage-clover build/logs/clover.xml
addons:
    code_climate:
        repo_token: c2fdad21c34ca6bd418009361ac42b686757cabccd579ab0d55e9a1d0da885c2